### PR TITLE
Added a small FIFO queue of input directions

### PR DESCRIPTION
**Pull request by freiguy1**
Now the player can make sharp turns by pressing two direction buttons in quick succession!

I also switched LEFT and RIGHT directions because the code was hooked up in reverse (when snake moving left on screen, direction was RIGHT).

This is my second night of zig, so please be critical! 

Thanks!

### CODE REVIEW

**Comment by fabioarnold** [comment]
Hi @freiguy1 , 
thanks so much for your pull request. :)

How did I mix up left and right? 🙈 Probably while refactoring the C version and getting east and west mixed up... https://github.com/fabioarnold/snake/blob/master/main.c#L376

Nice idea for adding the helper method `is_opposite` to the Direction enum. When writing this I didn't know much Zig, yet. Though you might want to change your method names to camelCase. Types in Zig are CamelCase, variables snake_case and functions always camelCase.

I like the idea of a FIFO queue for inputs. I think subjectively the game plays better now. :) When turning 180° your second input doesn't get "eaten", right? So, a queue length of 2 might already be sufficient. You could solve this using just two variables (dir and next_dir or queued_dir?). Or do you have another use-case where you want to buffer inputs for longer? If you prefer to use a data structure checkout https://github.com/ziglang/zig/blob/master/lib/std/fifo.zig in the standard library. You can initialize it with a fixed buffer and simply use it with writeItem and readItem, which would make the code more readable I guess.

**Comment by freiguy1** [comment]
Whoa, I'm surprised about the casing for functions/methods. Good catch.

You know, I went with 4 for a queue length because perhaps someone wants to make a maneuver which is more than 2 turns. I was thinking something like 

```
 _______
|         F
|FS
| S
| S
| S
|
```
F is food, S is snake, and the snake is traveling upward. The player can execute the sequence Left, Up, Right quickly to grab the food and get out to the other food. It's possible that those three direction keys could be hit in 1 tick. Anyway I suppose this could be tested by lowering the length to 2 and testing!

I stopped with a length of 4 because I just guessed pressing 4 directions in 1 tick probably wouldn't happen often.

Let me know what you think. At least that'd be quite easy to change.

I think I will try using `std.fifo`! Good suggestion. I noticed I need to send an allocator to `init`. I've never dealt with an allocator. I'll use the same one you use. Does this mean I need to `defer deinit()` somewhere? I'm a little lost to how the manual memory managements works.

**Comment by freiguy1** [comment]
Okay so I removed the FIFO queue of directions in favor of just 2 fields like you said. It seems to play the exact same, so the scenario I said above isn't a valid reason for more than 1 'queued' next direction. This makes it much simpler (no complicated queuing and de-queuing). Let me know any other comments!

**Comment by fabioarnold** [comment]
Good stuff. Thank you! 😄 

std.LinearFifo has three memory types: Static, Slice and Dynamic. You only need an allocator in case you're using the dynamic type. Else you can specify the maximum size ahead. Yes, `deinit` frees the memory of the fifo data structure. The basics of manual memory management are simple: you ask the allocator for memory and if you don't need that memory anymore you just free it.

**Pull request merged**
